# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, QThread, pyqtSignal
import main as backend
import time

POS_DISCORD_CHAT = []


class progressThreadPokemon(QThread):
    progress_update = pyqtSignal(int)  # or pyqtSignal(int)

    def __init__(self):
        QThread.__init__(self)

    def __del__(self):
        self.wait()

    def run(self):
        # your logic here
        while 1:
            maxVal = 1  # NOTE THIS CHANGED to 1 since updateProgressBar was updating the value by 1 every time
            self.progress_update.emit(maxVal)  # self.emit(SIGNAL('PROGRESS'), maxVal)
            # Tell the thread to sleep for 1 second and let other things run
            time.sleep(1)


class Ui_MainWindow(object):
    def __init__(self) -> None:
        super().__init__()
        self.progress_thread_pokemon = progressThreadPokemon()
        self.progress_thread_fish = progressThreadPokemon()

    def update_pos(self):
        self.pos = backend.find_discord_chat()
        self.pos_str = "X = " + str(self.pos[0]) + " | Y = " + str(self.pos[1])

    def pokemon_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, ";pokemon")
            self.pokeball_widget.show()
            self.main_widget.hide()
            self.progress_thread_pokemon.start()
            self.progress_thread_pokemon.progress_update.connect(
                self.update_pokemon_progressBar
            )
            self.pokemon_pushButton.setEnabled(False)

    def update_pokemon_progressBar(self, maxVal):
        self.pokemon_progressBar.setValue(self.pokemon_progressBar.value() + maxVal)
        print("pokemon_progressBar", self.pokemon_progressBar.value())
        if maxVal == 0:
            self.pokemon_progressBar.setValue(self.pokemon_progressBar.maximum())
        if self.pokemon_progressBar.value() == self.pokemon_progressBar.maximum():
            self.progress_thread_pokemon.disconnect()
            self.pokemon_progressBar.setValue(0)
            self.pokemon_pushButton.setEnabled(True)

    def pokemon_fish_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, ";fish")
            self.pokeball_fish_widget.show()
            self.main_widget.hide()
            self.progress_thread_fish.start()
            self.progress_thread_fish.progress_update.connect(
                self.update_fish_progressBar
            )
            self.fish_pushButton.setEnabled(False)

    def update_fish_progressBar(self, maxVal):
        self.fish_progressBar.setValue(self.fish_progressBar.value() + maxVal)
        print("fish_progressBar", self.fish_progressBar.value())
        if maxVal == 0:
            self.fish_progressBar.setValue(self.fish_progressBar.maximum())
        if self.fish_progressBar.value() == self.fish_progressBar.maximum():
            self.progress_thread_fish.disconnect()
            self.fish_progressBar.setValue(0)
            self.fish_pushButton.setEnabled(True)

    def pokeball_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, "pb")
            self.main_widget.show()
            self.pokeball_widget.hide()

    def greatball_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, "gb")
            self.main_widget.show()
            self.pokeball_widget.hide()

    def ultraball_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, "ub")
            self.main_widget.show()
            self.pokeball_widget.hide()

    def premierball_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, "prb")
            self.main_widget.show()
            self.pokeball_widget.hide()

    def masterball_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, "mb")
            self.main_widget.show()
            self.pokeball_widget.hide()

    def cancel_pushButton_fonction(self):
        self.main_widget.show()
        self.pokeball_widget.hide()

    def pull_fish_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, "pull")

    def pokeball_fish_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, "pb")
            self.pokeball_fish_widget.hide()
            self.main_widget.show()

    def greatball_fish_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, "gb")
            self.pokeball_fish_widget.hide()
            self.main_widget.show()

    def ultraball_fish_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, "ub")
            self.pokeball_fish_widget.hide()
            self.main_widget.show()

    def premierball_fish_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, "prb")
            self.pokeball_fish_widget.hide()
            self.main_widget.show()

    def diveball_fish_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, "db")
            self.pokeball_fish_widget.hide()
            self.main_widget.show()

    def masterball_fish_pushButton_fonction(self):
        self.update_pos()
        if self.pos != [0, 0]:
            backend.send_on_discord_chat(self.pos, "mb")
            self.pokeball_fish_widget.hide()
            self.main_widget.show()

    def cancel_fish_pushButton_fonction(self):
        self.pokeball_fish_widget.hide()
        self.main_widget.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(473, 436)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(0, 0, 471, 431))
        self.main_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_widget.setAutoFillBackground(True)
        self.main_widget.setObjectName("main_widget")
        self.pokemon_pushButton = QtWidgets.QPushButton(self.main_widget)
        self.pokemon_pushButton.setGeometry(QtCore.QRect(40, 50, 81, 81))
        self.pokemon_pushButton.setObjectName("pokemon_pushButton")
        self.fish_pushButton = QtWidgets.QPushButton(self.main_widget)
        self.fish_pushButton.setGeometry(QtCore.QRect(200, 50, 81, 81))
        self.fish_pushButton.setObjectName("fish_pushButton")
        self.pokemon_progressBar = QtWidgets.QProgressBar(self.main_widget)
        self.pokemon_progressBar.setGeometry(QtCore.QRect(30, 130, 101, 23))
        self.pokemon_progressBar.setProperty("value", 0)
        self.pokemon_progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.pokemon_progressBar.setObjectName("pokemon_progressBar")
        self.fish_progressBar = QtWidgets.QProgressBar(self.main_widget)
        self.fish_progressBar.setGeometry(QtCore.QRect(190, 130, 101, 23))
        self.fish_progressBar.setProperty("value", 0)
        self.fish_progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.fish_progressBar.setObjectName("fish_progressBar")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.main_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 400, 221, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.discord_chat_pushButton = QtWidgets.QPushButton(
            self.horizontalLayoutWidget
        )
        self.discord_chat_pushButton.setEnabled(True)
        self.discord_chat_pushButton.setObjectName("discord_chat_pushButton")
        self.horizontalLayout.addWidget(self.discord_chat_pushButton)
        self.discord_chat_x_y = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.discord_chat_x_y.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.discord_chat_x_y.setAlignment(QtCore.Qt.AlignCenter)
        self.discord_chat_x_y.setObjectName("discord_chat_x_y")
        self.horizontalLayout.addWidget(self.discord_chat_x_y)
        self.battle_progressBar = QtWidgets.QProgressBar(self.main_widget)
        self.battle_progressBar.setGeometry(QtCore.QRect(340, 130, 101, 23))
        self.battle_progressBar.setProperty("value", 0)
        self.battle_progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.battle_progressBar.setObjectName("battle_progressBar")
        self.battle_pushButton = QtWidgets.QPushButton(self.main_widget)
        self.battle_pushButton.setGeometry(QtCore.QRect(350, 50, 81, 81))
        self.battle_pushButton.setObjectName("battle_pushButton")
        self.pokeball_widget = QtWidgets.QWidget(self.centralwidget)
        self.pokeball_widget.setGeometry(QtCore.QRect(0, 0, 471, 431))
        self.pokeball_widget.setVisible(False)
        self.pokeball_widget.setObjectName("pokeball_widget")
        self.pokeball_pushButton = QtWidgets.QPushButton(self.pokeball_widget)
        self.pokeball_pushButton.setGeometry(QtCore.QRect(40, 50, 81, 81))
        self.pokeball_pushButton.setObjectName("pokeball_pushButton")
        self.greatball_pushButton = QtWidgets.QPushButton(self.pokeball_widget)
        self.greatball_pushButton.setGeometry(QtCore.QRect(200, 50, 81, 81))
        self.greatball_pushButton.setObjectName("greatball_pushButton")
        self.ultraball_pushButton = QtWidgets.QPushButton(self.pokeball_widget)
        self.ultraball_pushButton.setGeometry(QtCore.QRect(360, 50, 81, 81))
        self.ultraball_pushButton.setObjectName("ultraball_pushButton")
        self.premierball_pushButton = QtWidgets.QPushButton(self.pokeball_widget)
        self.premierball_pushButton.setGeometry(QtCore.QRect(120, 160, 81, 81))
        self.premierball_pushButton.setObjectName("premierball_pushButton")
        self.masterball_pushButton = QtWidgets.QPushButton(self.pokeball_widget)
        self.masterball_pushButton.setGeometry(QtCore.QRect(280, 160, 81, 81))
        self.masterball_pushButton.setObjectName("masterball_pushButton")
        self.cancel_pushButton = QtWidgets.QPushButton(self.pokeball_widget)
        self.cancel_pushButton.setGeometry(QtCore.QRect(440, 400, 31, 31))
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.pokeball_fish_widget = QtWidgets.QWidget(self.centralwidget)
        self.pokeball_fish_widget.setGeometry(QtCore.QRect(0, 0, 471, 431))
        self.pokeball_fish_widget.setVisible(False)
        self.pokeball_fish_widget.setObjectName("pokeball_fish_widget")
        self.pokeball_fish_pushButton = QtWidgets.QPushButton(self.pokeball_fish_widget)
        self.pokeball_fish_pushButton.setGeometry(QtCore.QRect(40, 180, 81, 81))
        self.pokeball_fish_pushButton.setObjectName("pokeball_fish_pushButton")
        self.greatball_fish_pushButton = QtWidgets.QPushButton(
            self.pokeball_fish_widget
        )
        self.greatball_fish_pushButton.setGeometry(QtCore.QRect(200, 180, 81, 81))
        self.greatball_fish_pushButton.setObjectName("greatball_fish_pushButton")
        self.ultraball_fish_pushButton = QtWidgets.QPushButton(
            self.pokeball_fish_widget
        )
        self.ultraball_fish_pushButton.setGeometry(QtCore.QRect(360, 180, 81, 81))
        self.ultraball_fish_pushButton.setObjectName("ultraball_fish_pushButton")
        self.premierball_fish_pushButton = QtWidgets.QPushButton(
            self.pokeball_fish_widget
        )
        self.premierball_fish_pushButton.setGeometry(QtCore.QRect(40, 290, 81, 81))
        self.premierball_fish_pushButton.setObjectName("premierball_fish_pushButton")
        self.masterball_fish_pushButton = QtWidgets.QPushButton(
            self.pokeball_fish_widget
        )
        self.masterball_fish_pushButton.setGeometry(QtCore.QRect(360, 290, 81, 81))
        self.masterball_fish_pushButton.setObjectName("masterball_fish_pushButton")
        self.pull_fish_pushButton = QtWidgets.QPushButton(self.pokeball_fish_widget)
        self.pull_fish_pushButton.setGeometry(QtCore.QRect(40, 40, 401, 81))
        self.pull_fish_pushButton.setObjectName("pull_fish_pushButton")
        self.cancel_fish_pushButton = QtWidgets.QPushButton(self.pokeball_fish_widget)
        self.cancel_fish_pushButton.setGeometry(QtCore.QRect(440, 400, 31, 31))
        self.cancel_fish_pushButton.setObjectName("cancel_fish_pushButton")
        self.diveball_fish_pushButton = QtWidgets.QPushButton(self.pokeball_fish_widget)
        self.diveball_fish_pushButton.setGeometry(QtCore.QRect(200, 290, 81, 81))
        self.diveball_fish_pushButton.setObjectName("diveball_fish_pushButton")
        self.battle_widget = QtWidgets.QWidget(self.centralwidget)
        self.battle_widget.setGeometry(QtCore.QRect(0, 0, 471, 431))
        self.battle_widget.setObjectName("battle_widget")
        self.battle_widget.setVisible(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.battle_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 131, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gym_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.gym_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.gym_verticalLayout.setObjectName("gym_verticalLayout")
        self.gym_kanto_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.gym_kanto_pushButton.setObjectName("gym_kanto_pushButton")
        self.gym_verticalLayout.addWidget(self.gym_kanto_pushButton)
        self.gym_johto_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.gym_johto_pushButton.setObjectName("gym_johto_pushButton")
        self.gym_verticalLayout.addWidget(self.gym_johto_pushButton)
        self.gym_hoenn_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.gym_hoenn_pushButton.setObjectName("gym_hoenn_pushButton")
        self.gym_verticalLayout.addWidget(self.gym_hoenn_pushButton)
        self.gym_sinnoh_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.gym_sinnoh_pushButton.setObjectName("gym_sinnoh_pushButton")
        self.gym_verticalLayout.addWidget(self.gym_sinnoh_pushButton)
        self.gym_unova_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.gym_unova_pushButton.setObjectName("gym_unova_pushButton")
        self.gym_verticalLayout.addWidget(self.gym_unova_pushButton)
        self.gym_kalos_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.gym_kalos_pushButton.setObjectName("gym_kalos_pushButton")
        self.gym_verticalLayout.addWidget(self.gym_kalos_pushButton)
        self.elite_four_label = QtWidgets.QLabel(self.battle_widget)
        self.elite_four_label.setGeometry(QtCore.QRect(210, 30, 47, 13))
        self.elite_four_label.setObjectName("elite_four_label")
        self.champions_label = QtWidgets.QLabel(self.battle_widget)
        self.champions_label.setGeometry(QtCore.QRect(370, 30, 47, 13))
        self.champions_label.setObjectName("champions_label")
        self.gym_label = QtWidgets.QLabel(self.battle_widget)
        self.gym_label.setGeometry(QtCore.QRect(60, 30, 47, 13))
        self.gym_label.setObjectName("gym_label")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.battle_widget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(170, 40, 131, 311))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.elite_four_verticalLayout = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_4
        )
        self.elite_four_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.elite_four_verticalLayout.setObjectName("elite_four_verticalLayout")
        self.elite_four_kanto_pushButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_4
        )
        self.elite_four_kanto_pushButton.setObjectName("elite_four_kanto_pushButton")
        self.elite_four_verticalLayout.addWidget(self.elite_four_kanto_pushButton)
        self.elite_four_johto_pushButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_4
        )
        self.elite_four_johto_pushButton.setObjectName("elite_four_johto_pushButton")
        self.elite_four_verticalLayout.addWidget(self.elite_four_johto_pushButton)
        self.elite_four_hoenn_pushButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_4
        )
        self.elite_four_hoenn_pushButton.setObjectName("elite_four_hoenn_pushButton")
        self.elite_four_verticalLayout.addWidget(self.elite_four_hoenn_pushButton)
        self.elite_four_sinnoh_pushButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_4
        )
        self.elite_four_sinnoh_pushButton.setObjectName("elite_four_sinnoh_pushButton")
        self.elite_four_verticalLayout.addWidget(self.elite_four_sinnoh_pushButton)
        self.elite_four_unova_pushButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_4
        )
        self.elite_four_unova_pushButton.setObjectName("elite_four_unova_pushButton")
        self.elite_four_verticalLayout.addWidget(self.elite_four_unova_pushButton)
        self.elite_four_kalos_pushButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_4
        )
        self.elite_four_kalos_pushButton.setObjectName("elite_four_kalos_pushButton")
        self.elite_four_verticalLayout.addWidget(self.elite_four_kalos_pushButton)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.battle_widget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(330, 40, 131, 311))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.champions_verticalLayout = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_5
        )
        self.champions_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.champions_verticalLayout.setObjectName("champions_verticalLayout")
        self.champions_kanto_pushButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_5
        )
        self.champions_kanto_pushButton.setObjectName("champions_kanto_pushButton")
        self.champions_verticalLayout.addWidget(self.champions_kanto_pushButton)
        self.champions_johto_pushButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_5
        )
        self.champions_johto_pushButton.setObjectName("champions_johto_pushButton")
        self.champions_verticalLayout.addWidget(self.champions_johto_pushButton)
        self.champions_hoenn_pushButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_5
        )
        self.champions_hoenn_pushButton.setObjectName("champions_hoenn_pushButton")
        self.champions_verticalLayout.addWidget(self.champions_hoenn_pushButton)
        self.champions_sinnoh_pushButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_5
        )
        self.champions_sinnoh_pushButton.setObjectName("champions_sinnoh_pushButton")
        self.champions_verticalLayout.addWidget(self.champions_sinnoh_pushButton)
        self.champions_unova_pushButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_5
        )
        self.champions_unova_pushButton.setObjectName("champions_unova_pushButton")
        self.champions_verticalLayout.addWidget(self.champions_unova_pushButton)
        self.champions_kalos_pushButton = QtWidgets.QPushButton(
            self.verticalLayoutWidget_5
        )
        self.champions_kalos_pushButton.setObjectName("champions_kalos_pushButton")
        self.champions_verticalLayout.addWidget(self.champions_kalos_pushButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.battle_widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 370, 451, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.npc_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.npc_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.npc_horizontalLayout.setObjectName("npc_horizontalLayout")
        self.npc_xp_1_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.npc_xp_1_pushButton.setObjectName("npc_xp_1_pushButton")
        self.npc_horizontalLayout.addWidget(self.npc_xp_1_pushButton)
        self.npc_xp_2_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.npc_xp_2_pushButton.setObjectName("npc_xp_2_pushButton")
        self.npc_horizontalLayout.addWidget(self.npc_xp_2_pushButton)
        self.cancel_battle_pushButton = QtWidgets.QPushButton(self.battle_widget)
        self.cancel_battle_pushButton.setGeometry(QtCore.QRect(440, 400, 31, 31))
        self.cancel_battle_pushButton.setObjectName("cancel_battle_pushButton")
        self.main_widget.raise_()
        self.pokeball_fish_widget.raise_()
        self.pokeball_widget.raise_()
        self.battle_widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionDiscord_chat = QtWidgets.QAction(MainWindow)
        self.actionDiscord_chat.setCheckable(False)
        self.actionDiscord_chat.setObjectName("actionDiscord_chat")

        self.update_pos()

        self.retranslateUi(MainWindow)

        ###
        ### POKEMON
        ###

        self.pokemon_pushButton.released.connect(self.pokemon_pushButton_fonction)
        self.pokeball_pushButton.released.connect(self.pokeball_pushButton_fonction)
        self.greatball_pushButton.released.connect(self.greatball_pushButton_fonction)
        self.ultraball_pushButton.released.connect(self.ultraball_pushButton_fonction)
        self.premierball_pushButton.released.connect(
            self.premierball_pushButton_fonction
        )
        self.masterball_pushButton.released.connect(self.masterball_pushButton_fonction)
        self.cancel_pushButton.released.connect(self.cancel_pushButton_fonction)

        ###
        ### FISHING
        ###

        self.fish_pushButton.released.connect(self.pokemon_fish_pushButton_fonction)
        self.pull_fish_pushButton.released.connect(self.pull_fish_pushButton_fonction)
        self.pokeball_fish_pushButton.released.connect(
            self.pokeball_fish_pushButton_fonction
        )
        self.greatball_fish_pushButton.released.connect(
            self.greatball_fish_pushButton_fonction
        )
        self.ultraball_fish_pushButton.released.connect(
            self.ultraball_fish_pushButton_fonction
        )
        self.premierball_fish_pushButton.released.connect(
            self.premierball_fish_pushButton_fonction
        )
        self.diveball_fish_pushButton.released.connect(
            self.diveball_fish_pushButton_fonction
        )
        self.masterball_fish_pushButton.released.connect(
            self.masterball_fish_pushButton_fonction
        )
        self.cancel_fish_pushButton.released.connect(
            self.cancel_fish_pushButton_fonction
        )

        ###
        ### BATTLE
        ###

        # self.gym_kanto_pushButton.released.connect()
        # self.gym_johto_pushButton.released.connect()
        # self.gym_hoenn_pushButton.released.connect()
        # self.gym_sinnoh_pushButton.released.connect()
        # self.gym_unova_pushButton.released.connect()
        # self.gym_kalos_pushButton.released.connect()
        # self.elite_four_kanto_pushButton.released.connect()
        # self.elite_four_johto_pushButton.released.connect()
        # self.elite_four_hoenn_pushButton.released.connect()
        # self.elite_four_sinnoh_pushButton.released.connect()
        # self.elite_four_unova_pushButton.released.connect()
        # self.elite_four_kalos_pushButton.released.connect()
        # self.champions_kanto_pushButton.released.connect()
        # self.champions_johto_pushButton.released.connect()
        # self.champions_hoenn_pushButton.released.connect()
        # self.champions_sinnoh_pushButton.released.connect()
        # self.champions_unova_pushButton.released.connect()
        # self.champions_kalos_pushButton.released.connect()
        # self.npc_xp_1_pushButton.released.connect()
        # self.npc_xp_2_pushButton.released.connect()
        # self.cancel_battle_pushButton.released.connect()

        ###
        self.discord_chat_pushButton.released.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pokemon_pushButton.setText(_translate("MainWindow", "Pokemon"))
        self.fish_pushButton.setText(_translate("MainWindow", "Fish"))
        self.discord_chat_pushButton.setText(_translate("MainWindow", "Discord Chat"))
        self.discord_chat_x_y.setText(_translate("MainWindow", "X = | Y ="))
        self.battle_pushButton.setText(_translate("MainWindow", "Battle"))
        self.pokeball_pushButton.setText(_translate("MainWindow", "Pokepall"))
        self.greatball_pushButton.setText(_translate("MainWindow", "Greatball"))
        self.ultraball_pushButton.setText(_translate("MainWindow", "Ultraball"))
        self.premierball_pushButton.setText(_translate("MainWindow", "Premierball"))
        self.masterball_pushButton.setText(_translate("MainWindow", "Masterball"))
        self.cancel_pushButton.setText(_translate("MainWindow", "X"))
        self.pokeball_fish_pushButton.setText(_translate("MainWindow", "Pokepall"))
        self.greatball_fish_pushButton.setText(_translate("MainWindow", "Greatball"))
        self.ultraball_fish_pushButton.setText(_translate("MainWindow", "Ultraball"))
        self.premierball_fish_pushButton.setText(
            _translate("MainWindow", "Premierball")
        )
        self.masterball_fish_pushButton.setText(_translate("MainWindow", "Masterball"))
        self.pull_fish_pushButton.setText(_translate("MainWindow", "PULL"))
        self.cancel_fish_pushButton.setText(_translate("MainWindow", "X"))
        self.diveball_fish_pushButton.setText(_translate("MainWindow", "Diveball"))
        self.gym_kanto_pushButton.setText(_translate("MainWindow", "Kanto"))
        self.gym_johto_pushButton.setText(_translate("MainWindow", "Johto"))
        self.gym_hoenn_pushButton.setText(_translate("MainWindow", "Hoenn"))
        self.gym_sinnoh_pushButton.setText(_translate("MainWindow", "Sinnoh"))
        self.gym_unova_pushButton.setText(_translate("MainWindow", "Unova"))
        self.gym_kalos_pushButton.setText(_translate("MainWindow", "Kalos"))
        self.elite_four_label.setText(_translate("MainWindow", "Elite Four"))
        self.champions_label.setText(_translate("MainWindow", "Champions"))
        self.gym_label.setText(_translate("MainWindow", "Gym"))
        self.elite_four_kanto_pushButton.setText(_translate("MainWindow", "Kanto"))
        self.elite_four_johto_pushButton.setText(_translate("MainWindow", "Johto"))
        self.elite_four_hoenn_pushButton.setText(_translate("MainWindow", "Hoenn"))
        self.elite_four_sinnoh_pushButton.setText(_translate("MainWindow", "Sinnoh"))
        self.elite_four_unova_pushButton.setText(_translate("MainWindow", "Unova"))
        self.elite_four_kalos_pushButton.setText(_translate("MainWindow", "Kalos"))
        self.champions_kanto_pushButton.setText(_translate("MainWindow", "Kanto"))
        self.champions_johto_pushButton.setText(_translate("MainWindow", "Johto"))
        self.champions_hoenn_pushButton.setText(_translate("MainWindow", "Hoenn"))
        self.champions_sinnoh_pushButton.setText(_translate("MainWindow", "Sinnoh"))
        self.champions_unova_pushButton.setText(_translate("MainWindow", "Unova"))
        self.champions_kalos_pushButton.setText(_translate("MainWindow", "Kalos"))
        self.npc_xp_1_pushButton.setText(
            _translate("MainWindow", "NPC 675725560470831125")
        )
        self.npc_xp_2_pushButton.setText(
            _translate("MainWindow", "NPC 508692505810698241")
        )
        self.cancel_battle_pushButton.setText(_translate("MainWindow", "X"))
        self.actionDiscord_chat.setText(_translate("MainWindow", "Discord chat"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
